spring:
  application:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${ISS}
          audience: audience
          jwk-set-uri: ${KEYSTORE}
          jwk-set-ttl: 300
          jws-algorithm: RS256
          secret-key: ${SECRET_KEY}

logging:
  level:
    root: INFO
